[package]
name = "naiveqa_medium"
version = "0.1.0"
authors = ["Cno <dsyourshy@qq.com>"]
edition = "2018"

[dependencies]
websocket = "0.24.0"
argparse = "0.2.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }